CREATE DATABASE loja_virtual;

CREATE TABLE PRODUTO (id INT AUTO_INCREMENT, nome VARCHAR(50) NOT NULL, descricao VARCHAR(255), PRIMARY KEY (id)) Engine = InnoDB;

INSERT INTO PRODUTO (nome, descricao) VALUES ('NOTEBOOK', 'NOTEBOOK SAMSUNG'); 
INSERT INTO PRODUTO (nome, descricao) VALUES ('CARRO', 'CARRO CONSUL'); 

select * from produto;
select * from CATEGORIA;


CREATE TABLE IF NOT EXISTS CATEGORIA (
ID INT auto_increment,
NOME VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)


) ENGINE = InnoDB;

INSERT INTO CATEGORIA (NOME) VALUES ("ELETRODOMESTICOS");

ALTER TABLE PRODUTO ADD COLUMN CATEGORIA_ID INT;
ALTER TABLE PRODUTO ADD FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID);
UPDATE PRODUTO SET CATEGORIA_ID = 3 WHERE ID = 3;